# Generated by Django 3.2.13 on 2022-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_credit',
            field=models.BooleanField(default=False, verbose_name='Is Credit?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='Is Transaction Pending?'),
        ),
    ]
