# Generated by Django 3.2.13 on 2022-06-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220609_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='transaction',
            name='not_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
