# Generated by Django 3.2.13 on 2022-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi_ids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi_id',
            name='upi_pin',
            field=models.CharField(max_length=1000),
        ),
    ]
