# Generated by Django 3.2.13 on 2022-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi_ids', '0002_alter_upi_id_upi_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi_id',
            name='scan_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='upi/qr_codes'),
        ),
    ]
