# Generated by Django 3.2.13 on 2022-06-08 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upi_ids', '0003_alter_upi_id_scan_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UPI_ID',
            new_name='UPIS',
        ),
    ]
