# Generated by Django 3.2.13 on 2022-06-08 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upi_ids', '0004_rename_upi_id_upis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UPIS',
            new_name='UPI',
        ),
    ]
