# Generated by Django 3.2.13 on 2022-06-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi_ids', '0005_rename_upis_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='upi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
